---
- name: install mysql-server
  ansible.builtin.include_tasks:
    file: install.yml

- name: Setup zabbiz database
  ansible.builtin.include_tasks:
    file: db_zabbix.yml

- name: Setup minecraft database
  ansible.builtin.include_tasks:
    file: db_minecraft.yml
